name: reset_exercises
on: 
  workflow_dispatch:
jobs:
  close-pulls:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - run: | 
          for p in $(gh pr list --json number --jq '.[].number')l do
            echo "hello" $p
          done
            



