name: reset_exercises
on: 
  workflow_dispatch:
jobs:
  close-pulls:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - run: | 
          gh pr list --state open



