name: create_exercises
on: 
  workflow_dispatch:
   inputs: 
      language:
        description: 'Language'
        required: true
        default: text
        type: choice
        options:
        - text 
        - python
        - fortran
permissions: write-all
jobs:
  create-pulls-matrix:
    strategy:
      matrix:
        exercise: [1, 2, 3]
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - run: |
          echo "Language: ${{ inputs.language }}"
          echo "Exercise: ${{ matrix.exercise }}"
      # checkout repo
      - uses: actions/checkout@v3
      - name: create lablel for issues
        run: gh label create ${{ inputs.language }} -f
      - name: create issue for exercise ${{ inputs.exercise }}
        run: gh issue create --title "Exercise ${{ matrix.exercise }} ${{ inputs.language }}" --body-file "guts/${{ inputs.language }}-ex${{ matrix.exercise }}-issue.md" --label ${{ inputs.language }}
      - name: create pull request for exercise ${{ matrix.exercise }}
        run: gh pr create -B main -H "${{ inputs.language }}-${{ matrix.exercise }}" --title 'Exercise ${{ matrix.exercise }} ${{ inputs.language }}. ' --body ' ${{ inputs.language }}'
