name: open_pull_ex
on: workflow_dispatch
permissions: write-all
jobs:
  create-pulls:
    runs-on: ubuntu-latest
    steps:
      # checkout repo
      - uses: actions/checkout@v3
        
      - name: create pull request for exercise 1
        run: gh pr create -B main -H pull1 --title 'Exercise 1. Text' --body 'Created by Github action'
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
