name: open_pull_ex
on: 
  workflow_dispatch:
   inputs: 
      language:
        description: 'Language'
        required: true
        default: text
        type: choice
        options:
        - text 
        - python
        - fortran
permissions: write-all
jobs:
  create-pulls:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - run: |
          echo "Language: ${{ inputs.language }}"
      # checkout repo
      - uses: actions/checkout@v3
      - name: create issue for exercise 1
        run: gh issue create -a @me --title "Exercise 1"        
      - name: create pull request for exercise 1
        run: gh pr create -B main -H ${{ inputs.language }} --title 'Exercise 1${{ inputs.language }}. ' --body 'Created by Github action ${{ inputs.language }}'
