name: Update Changelog
on: create
jobs:
  updateChangelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Update Changelog
        run: |
           touch CHANGELOG.md
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: update changelog
          title: Update Changelog
          body: Update changelog to reflect release changes
          branch: update-changelog
          base: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
